### ISSUE TITLE
Pwndbg raise exception with newest capstone engine

### ISSUE THREAD

**Issue by windcarp** [zachriggle/pwndbg#29]
Excuse me but something went wrong with pwndbg which I installed recently, maybe something is wrong with /disasm/color.py(line 11), capstone has moved target_constant attribute, anyway thanks a lot to your wonderful work!

**Comment by zachriggle** [comment]
I would recommend updating `pwndbg`, `capstone`, and `unicorn` and trying again.

If the error persists, please provide the full exception, as well as running the following command:

```sh
for dir in unicorn capstone pwndbg; do 
  pushd $dir
  echo "$dir: $(git log --oneline -1)"
  popd
done
```

For reference, current tip-of-tree uses the following versions.  I did not notice any problem.

```
unicorn: 4b3bbe4 Merge pull request #549 from eqv/fix_go
capstone: 4d36deb fix #673
pwndbg: d13b9e8 Add print_function to everything
```

**Comment by zachriggle** [comment]
I would recommend updating `pwndbg` and trying again.  In particular, I just added a `setup.sh` script to simplify the installation process.  Instead of getting Capstone and Unicorn separately, they are now tracked as Git submodules.

If the error persists, please provide the full exception, as well as running the command `python pwndbg/gitver.py`.

**Comment by windcarp** [comment]
Got it, and thank you for taking the time to reply!

**Comment by zachriggle** [comment]
Everything is working then?  Sounds like it, so I'm closing the issue.
